# Generated by Django 3.1 on 2021-05-12 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
                ('categoria', models.CharField(default='', max_length=255, verbose_name='Categoria')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
        ),
    ]
