# Generated by Django 3.1 on 2021-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
