# Generated by Django 3.1 on 2021-06-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Cat_Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='', max_length=255, verbose_name='Razon social')),
                ('telefono', models.CharField(default='', max_length=10, verbose_name='Telefono')),
                ('cp', models.CharField(default='', max_length=5, verbose_name='Codigo postal')),
                ('calle', models.CharField(default='', max_length=255, verbose_name='Calle')),
                ('no_ext', models.CharField(default='', max_length=255, verbose_name='Numero exterior')),
                ('no_int', models.CharField(default='', max_length=255, verbose_name='Numero interior')),
                ('correo', models.EmailField(default='', max_length=255, verbose_name='Correo electronico')),
                ('colonia', models.CharField(default='', max_length=255, verbose_name='Colonia')),
                ('estado', models.CharField(default='', max_length=255, verbose_name='Estado')),
                ('pais', models.CharField(default='', max_length=255, verbose_name='Pais')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TBL_CATEGORIA_ALIMENTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre de la categoria')),
                ('tipo', models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo de la categoria')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=255, verbose_name='Nombre de la categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TBL_Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje')),
                ('id_estatus', models.BooleanField(default=True, verbose_name='Estado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='TBL_Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_numero_inventario', models.IntegerField(null=True, verbose_name='Numero Inventario')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('id_estatus', models.BooleanField(default=False, verbose_name='Estado')),
                ('precio_paquete', models.DecimalField(decimal_places=2, max_digits=99999, verbose_name='Precio del paquete')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=99999, verbose_name='Precio unitario')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_proveedores')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='TBL_COMBOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=99999, verbose_name='Precio')),
                ('id_estatus', models.BooleanField(default=True, verbose_name='Estado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('id_producto', models.ManyToManyField(to='Producto.CAT_Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
        migrations.AddField(
            model_name='cat_producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_categoria_alimentos'),
        ),
        migrations.CreateModel(
            name='CAT_ALIMENTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=99999, verbose_name='Precio')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_categoria_alimentos')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
