# Generated by Django 3.1 on 2021-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_combos',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='tbl_combos',
            name='id_producto',
            field=models.ManyToManyField(to='Producto.CAT_Producto', verbose_name='Producto'),
        ),
    ]
