# Generated by Django 3.1 on 2021-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20210531_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_producto',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
