# Generated by Django 3.1 on 2021-05-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_auto_20210531_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_combos',
            name='id_estatus',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
