# Generated by Django 3.1 on 2021-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_auto_20210531_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_promociones',
            name='id_estatus',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tbl_promociones',
            name='porcentaje',
            field=models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Porcentaje'),
        ),
    ]
