# Generated by Django 3.1 on 2021-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_auto_20210531_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_promociones',
            name='porcentaje',
            field=models.IntegerField(verbose_name='Porcentaje'),
        ),
    ]
