# Generated by Django 3.1 on 2021-06-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_auto_20210531_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_alimentos',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cat_producto',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cat_proveedores',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tbl_combos',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tbl_inventario',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tbl_promociones',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
