# Generated by Django 3.1 on 2021-06-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=25, verbose_name='')),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuarios',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=70, verbose_name='')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Ultimo ingreso')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUsuario')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre (S)')),
                ('apellido_paterno', models.CharField(default='', max_length=255, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(default='', max_length=255, verbose_name='Apellido Materno')),
                ('col', models.CharField(max_length=255, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero_ext', models.IntegerField(null=True, verbose_name='Numero exterior')),
                ('numero_cel', models.IntegerField(null=True, verbose_name='Teléfono celular')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Username')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion de usuatrio')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion de usuatrio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('id_typoUsuario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpleadosApp.typeuser')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='registro_Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fecha de inscripcion o salida de usuario',
                'verbose_name_plural': 'Fecha de salida o salida de usuario',
            },
        ),
    ]
