# Generated by Django 3.1 on 2021-05-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpleadosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualizacion de usuatrio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion de usuatrio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
