# Generated by Django 3.1 on 2021-05-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpleadosApp', '0002_auto_20210503_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_cel',
            field=models.IntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_ext',
            field=models.IntegerField(verbose_name='Numero Exterior'),
        ),
    ]
