# Generated by Django 3.1 on 2021-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpleadosApp', '0003_auto_20210507_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido_materno',
            field=models.CharField(default='', max_length=255, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='user',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=255, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
