# Generated by Django 3.1 on 2021-06-11 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0008_auto_20210604_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('mesa', models.CharField(default='', max_length=5, verbose_name='Mesa')),
                ('numero_orden', models.CharField(default='', max_length=255, verbose_name='Numero de orden')),
                ('entregado', models.BooleanField(default=False, verbose_name='Entregado')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('id_alimento', models.ManyToManyField(to='Producto.CAT_ALIMENTOS')),
                ('id_combo', models.ManyToManyField(to='Producto.TBL_COMBOS')),
                ('id_producto', models.ManyToManyField(to='Producto.CAT_Producto')),
                ('id_promocion', models.ManyToManyField(to='Producto.TBL_Promociones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
