# Generated by Django 3.1 on 2021-05-30 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('mesa', models.CharField(default='', max_length=255, verbose_name='Mesa')),
                ('numero_orden', models.CharField(default='', max_length=255, verbose_name='Numero de orden')),
                ('entregado', models.BooleanField(default=False, verbose_name='Entregado')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_alimentos')),
                ('id_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_combos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_producto')),
                ('id_promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_promociones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
