# Generated by Django 3.1 on 2021-06-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField(default=False, verbose_name='Entregado')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Hora del pedido')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('id_alimento', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_alimentos')),
                ('id_combo', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_combos')),
                ('id_producto', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_producto')),
                ('id_promocion', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_promociones')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TBL_MESA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField(verbose_name='Numero de mesa')),
                ('numero_orden', models.CharField(default='', max_length=255, verbose_name='Numero de orden')),
                ('slug', models.CharField(default='', max_length=255, verbose_name='Numero de orden')),
                ('id_cajero', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to=settings.AUTH_USER_MODEL)),
                ('id_mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesero', to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='MeserosApp.tbl_pedidos')),
            ],
        ),
    ]
