# Generated by Django 3.1 on 2021-06-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('MeserosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_alimento',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_alimentos'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_combo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_combos'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_producto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.cat_producto'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_promocion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_promociones'),
        ),
    ]
