# Generated by Django 3.1 on 2021-06-11 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_auto_20210604_1933'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MeserosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_alimento',
            field=models.ManyToManyField(blank=True, default='', to='Producto.CAT_ALIMENTOS'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_combo',
            field=models.ManyToManyField(blank=True, default='', to='Producto.TBL_COMBOS'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_producto',
            field=models.ManyToManyField(blank=True, default='', to='Producto.CAT_Producto'),
        ),
        migrations.RemoveField(
            model_name='tbl_pedidos',
            name='id_promocion',
        ),
        migrations.AddField(
            model_name='tbl_pedidos',
            name='id_promocion',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Producto.tbl_promociones'),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='mesa',
            field=models.CharField(choices=[{1, '1'}, {2, '2'}, {'3', 3}, {'4', 4}, {'5', 5}, {'6', 6}, {'7', 7}, {8, '8'}], default='', max_length=5, verbose_name='Mesa'),
        ),
    ]
