# Generated by Django 3.1 on 2021-06-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeserosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pedidos',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
