# Generated by Django 3.1 on 2021-06-11 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MeserosApp', '0002_auto_20210610_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbl_pedidos',
            name='mesa',
            field=models.CharField(default='', max_length=5, verbose_name='Mesa'),
        ),
    ]
