# Generated by Django 3.1 on 2021-06-17 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MeserosApp', '0002_auto_20210617_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mesa',
            name='id_cajero',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
