# Generated by Django 3.1 on 2021-05-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
                ('categoria', models.CharField(default='', max_length=255, verbose_name='Categoria')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
