# Generated by Django 3.1 on 2021-05-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_Cajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(default='', max_length=255, verbose_name='Sucursal')),
                ('numero_caja', models.IntegerField(verbose_name='Numero de caja')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='CAT_Denominacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(default='', max_length=255, verbose_name='Valor')),
                ('tipo_moneda', models.CharField(default='', max_length=255, verbose_name='Tipo de moneda')),
            ],
            options={
                'verbose_name': 'Denominacion',
                'verbose_name_plural': 'Denominaciones',
            },
        ),
        migrations.CreateModel(
            name='CAT_Tipo_Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de operacion',
                'verbose_name_plural': 'Tipos de operaciones',
            },
        ),
        migrations.CreateModel(
            name='TBL_Registro_Cajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CajerosApp.cat_cajas')),
                ('id_denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CajerosApp.cat_denominacion')),
                ('id_tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CajerosApp.cat_tipo_operacion')),
            ],
            options={
                'verbose_name': 'Registro de caja',
                'verbose_name_plural': 'Registro de cajas',
            },
        ),
    ]
