# Generated by Django 3.1 on 2021-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajerosApp', '0002_tbl_registro_cajas_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_cajas',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cat_denominacion',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cat_tipo_operacion',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tbl_registro_cajas',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
