# Generated by Django 3.1 on 2021-06-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajerosApp', '0003_auto_20210602_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_cajas',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cat_denominacion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cat_tipo_operacion',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tbl_registro_cajas',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
